server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: <>
            client-secret: <>
            scope: openid+profile+email
        provider:
          auth0:
            issuer-uri: <>